apiVersion: v1
kind: PersistentVolume
metadata:
  name: vspv01
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  vsphereVolume:
    volumePath: "[cmp1/cmpds1] volumes/vspv01"
    fsType: ext4
