#!/bin/bash
# Install kafka into a given Kubernetes namespace
# Requires the kubectl contexts set up for the given namespace, named as that namespace


## Config
KAFKA_YAML=kafkacluster-with-istio.yaml


## Functions
die() { echo "$@"; exit 1; }


## Main
namespace=$1
[[ $namespace ]] \
    || { echo "Usage: $0 NAMESPACE"; exit 1; }


helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com/

[[ -d kafka-operator ]] \
    || git clone https://github.com/banzaicloud/kafka-operator.git

cd kafka-operator

kubectl config use-context default \
    || die "Could not use context default. Ensure you have this namespace configured as a context named after the namespace"

if helm list --namespace default | grep -qP "prometheus-operator.*default"; then
    echo "prometheus-operator is already installed in namespace: default. Not doing it again"
else
    kubectl apply -n default -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/bundle.yaml \
        || die "Could not install prometheus-operator"
fi

kubectl config use-context $namespace \
    || die "Could not use context $namespace. Ensure you have this namespace configured as a context named after the namespace"

helm install kafka --namespace=$namespace banzaicloud-stable/kafka-operator -f ../$KAFKA_YAML \
    || die "Could not install kafka-operator"
